export const SET_CAROUSEL = 'SET_CAROUSEL';
export const SET_HE_THONG_RAP_CHIEU = 'SET_HE_THONG_RAP_CHIEU';
export const SET_FILM_SAP_CHIEU = 'SET_FILM_SAP_CHIEU';
export const SET_FILM_DANG_CHIEU = 'SET_FILM_DANG_CHIEU';
export const SET_DANH_SACH_PHIM = 'SET_DANH_SACH_PHIM';
export const SET_CHI_TIET_PHIM = 'SET_CHI_TIET_PHIM';
export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION';
export const SET_CHI_TIET_PHONG_VE = 'SET_CHI_TIET_PHONG_VE';
export const DAT_VE = 'DAT_VE';
export const SET_THONG_TIN_NGUOI_DUNG = 'SET_THONG_TIN_NGUOI_DUNG';
export const DISPLAY_LOADING = 'DISPLAY_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const CLEAR_THONG_TIN_DAT_VE = 'CLEAR_THONG_TIN_DAT_VE';
export const CHUYEN_TAB = 'CHUYEN_TAB';
export const CHANGE_TAB_POSITION = 'CHANGE_TAB_POSITION';
export const DAT_GHE = 'DAT_GHE';
export const SET_THONG_TIN_PHIM = 'SET_THONG_TIN_PHIM';
export const SET_DANH_SACH_NGUOI_DUNG = 'SET_DANH_SACH_NGUOI_DUNG';
export const SET_LOAI_NGUOI_DUNG = 'SET_LOAI_NGUOI_DUNG';
export const LAY_THONG_TIN_NGUOI_DUNG_USER = 'LAY_THONG_TIN_NGUOI_DUNG_USER';
export const TOGGLE_EDIT = 'TOGGLE_EDIT';
export const SHOW_MODAL = 'SHOW_MODAL';




